[package]
name = "winapi-easy"
version = "0.2.0-beta.0"
edition = "2021"
authors = ["Rolf Karp <rolf.karp@gmail.com>"]
license = "MIT OR Apache-2.0"

description = "A safe interface to various winapi functionality"
homepage = "https://github.com/rkarp/winapi-easy"
documentation = "https://docs.rs/winapi-easy"
readme = "README.md"
keywords = ["windows", "hotkey", "process", "taskbar"]
categories = ["os::windows-apis", "api-bindings", "gui"]

[package.metadata.docs.rs]
targets = ["x86_64-pc-windows-msvc"]

[dependencies]
ntapi = "0.3.6"
num_enum = "0.5.5"
wio = "0.2.2"

[dependencies.windows]
version = "0.34.0"
features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_System_WindowsProgramming",
    "Win32_UI_Shell",
]

[dependencies.winapi]
version = "0.3.9"
features = [
    "basetsd",
    "handleapi",
    "impl-debug",
    "impl-default",
    "ntdef",
    "objbase",
    "processthreadsapi",
    "shellapi",
    "shobjidl_core",
    "tlhelp32",
    "winbase",
    "wincon",
    "windowsx",
    "winerror",
    "winuser",
]

[dev-dependencies]
more-asserts = "0.2.1"
